name: Action RustDesk Windows Flutter (Github Action Cloud 专用) by.vancat

on:
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/_flutter-build-vc-onlyWin-clound.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly"
      target-os: "windows-latest"
