name: Action RustDesk Windows Flutter (本地自托管专用) by.vancat

on:
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/_flutter-build-vc-onlyWin-localHost.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly"
      target-os: "DESKTOP-JCNS1PB"
